.TH "LibModJpeg User Manual" 1.0.0 "27 May 2018" "LibModJpeg documentation"
.SH NAME
betterjpeg
.SH DESCRIPTION
Tool library for JPEG masking and composition in the DCT domain. 
.SH SYNOPSIS
betterjpeg [options] original.jpg modify.png result.jpg
.SH OPTIONS
.TP
-t N
threshold (default = 1)
.TP
-h
help
.SH EXAMPLES
betterjpeg myimage.jpg myimagemodify.png myimagemodify.jpg
.PP
gm compare -highlight-style assign -highlight-color lime -file myimagediff.jpg myimage.jpg myimagemodify.jpg
.SH COPYRIGHT
modjpeg (c) 2006+ Ingo Oppermann.
 All rights reserved.
.SH "SEE ALSO"
 modjpeg,
 gm,
 cjpeg,
 djpeg.
